### ISSUE TITLE
Path shows `undefined` after cancelled folder dialogue

### ISSUE THREAD

**Issue by montyanderson** [storjrd/backup#119] opened 2021-12-16 16:48 UTC
![image](https://user-images.githubusercontent.com/3048503/146413382-656336da-533b-4be5-8023-4bb8cb7eea7b.png)

**Comment by gabedealmeida** [comment] 2021-12-17 16:50
I can't reproduce this on an m1. Wonder if this is a Linux and/or Windows issue.

**Comment by gabedealmeida** [comment] 2022-01-10 19:50
Fixed by https://github.com/storjrd/backup/pull/120

**Closed** 2022-01-10 19:50 UTC
Labels: bug
